version: 2.1

jobs:
  run_ansible_playbook:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add build-base gcc musl-dev jpeg-dev zlib-dev libffi-dev cairo-dev pango-dev gdk-pixbuf-dev
      - run: apk add --no-cache python3 py3-pip python3-dev
      - run: pip install ansible
      - add_ssh_keys:
          fingerprints:
            - "2f:9c:51:ac:9a:ce:97:7a:20:b6:6d:35:0f:ea:73:2d"

      - run: ansible-playbook -i ansible-playbook/inventory.txt  ansible-playbook/main.yml

workflows:
  run_ansible_jobs:
    jobs:
      - run_ansible_playbook
