version: 2.1

jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run: aws cloudformation deploy
          --template-file cloudfront/bucket.yml
          --stack-name "${CIRCLE_WORKFLOW_ID:0:7}"
          --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}" NAME="bucket${CIRCLE_WORKFLOW_ID:0:7}"

  get_last_deployment_id:
    docker:
      - image: amazon/aws-cli
    steps:
      - run: yum install tar
      - run: aws cloudformation
          list-exports --query "Exports[?Name==\`PipelineID\`].Value"
          --no-paginate --output text > output.text

      - persist_to_workspace:
          root: /root/project
          paths:
            - output.txt

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: aws cloudformation deploy
          --template-file cloudfront/cloudfront.yml
          --stack-name production-distro
          --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"

  clean_up_old_front_end:
    docker:
      - image: amazon/aws-cli

    steps:
      - run: yum install tar
      - attach_workspace:
          at: /root/project

      - run: OldPipelineID=`cat output.txt`
      - run: aws s3 rm "s3://${OldPipelineID}" --recursive
      - run: aws cloudformation delete-stack --stack-name "${OldPipelineID}"

workflows:
  complete_cycle:
    jobs:
      - create_and_deploy_front_end
      - get_last_deployment_id:
          requires:
            - create_and_deploy_front_end
      - promote_to_production:
          requires:
            - get_last_deployment_id
      - clean_up_old_front_end:
          requires:
            - promote_to_production
