version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: pwd
      - run: ls
      - run: aws cloudformation create-stack --stack-name circleci --template-body file://../cloudformation/template.yml --region=us-west-2

workflows:
  print_hello_world:
    jobs:
      - create_infrastructure
