---
- name: Install apache
  shell: |
    yum update -y
    yum install -y httpd

- name: start apache
  shell: |
    systemctl start httpd
    systemctl enable httpd

- name: add index file
  copy:
    src: index.html
    dest: /var/www/html/index.html
    backup: yes
